### ISSUE TITLE
Game crashes often.

### ISSUE THREAD

**Issue by jonahnm** [xiaoxiao921/DearImGuiInjection#1]
Self-explanatory. Usually happens at launch or when interacting with UI.

**Comment by xiaoxiao921** [comment]
give player.log

**Comment by jonahnm** [comment]
[LogOutput.log](https://github.com/xiaoxiao921/DearImGuiInjection/files/11729360/LogOutput.log)
I assume you mean this, so here it is.

**Comment by jonahnm** [comment]
Ah, nevermind, turns out it was an error on my part, sorry to bother you.

**Comment by jonahnm** [comment]
Ok, nevermind this is still happening.
